### ISSUE TITLE
App concept?

### ISSUE THREAD

**Issue by BTBTravis** [redi-js-teachers/js_sprint_2020_final_project_hoangminhtuan-ops#1]
Hey @HoangMinhTuan-ops lets keep track of your app concept here.

What would you like to do for your final project?

here is an example of what another student is working on redi-js-teachers/js_sprint_2020_final_project_vidhya-eng#1

**Comment by HoangMinhTuan-ops** [comment]
Hi Travis,

thanks for asking me about the final project idea. I would like to work with a web app which will show the statistic of corona virus. There are three main data of confirmed cases, recovered cases and deaths cases. I also want to add some features for the web app, for example, showing charts, giving some hygiene tips for people to follow.

**Comment by BTBTravis** [comment]
Great idea @HoangMinhTuan-ops. 

Lets drill in further into your concept. 

1. Where will we get the data from?
1. Will users enter their location or what data countries data will be in the graphs?
1. Are there some different graphs from the standard one we see in the news you would like to do?
1. How is the site dynamic?


Please create a specific list of features your app will have

**Comment by BTBTravis** [comment]
Also found a bunch of corona related APIs here https://www.programmableweb.com/category/coronavirus%2Bcovid-19/apis?category=29999%2C30105

**Comment by HoangMinhTuan-ops** [comment]
thank you for your suggestions, I'm thinking of add some more features besides the statistics.
The users can choose the location/ country from a dropdown, this can avoid typo mistake from input and save time. Although the cases will be displayed separatedly, I still want to add a bar chart for more general view, there will be one bar chart as standard.
In addition, I have seen one student have an idea of making a weather app, am I allowed to add the weather as a small part of the website?

**Comment by MrTim** [comment]
Hey @HoangMinhTuan-ops,
Answering the last question - sure you can. But I would do it as an optional step. Because you want to focus on the corona cases statistics display.
As I understood you would focus on displaying information on users screen. Which is ok for sure!
I still don't really get the data displayed on the screen. Could you maybe create and example sketch with layout? This would simplify the process. 

For data visualisation I think you can use D3.js library- https://github.com/d3/d3

**Comment by HoangMinhTuan-ops** [comment]
Yes that's right, I'm just come up my mind with that idea but considering it as an option. 
For the display of the data, I start for now with 3 boxes with confirmed-, recovered-, and deaths-cases respectively. Yesterday I'm reading of Chart.js, however, D3 as you recommended looks much more powerful, I'm reading the docs, but did not get what svg is and how to use it. Thanks Ivan.

**Comment by MrTim** [comment]
If Chart.js looks easier and simpler as a start you can go with it!
Ok, I think we now know roughly what this project is about and a bit what would be inside.

Please create a first PR with description updated in Readme and base setup for the page.

**Comment by BTBTravis** [comment]
There has been no engagement in this issue by student in almost a month. Closing it.
